title: RE CVX SRT
author: Kapdap
email: kapdap@pm.me

product_name: RE CVX SRT
game_name: "Resident Evil: Code: Veronica"

show_excerpts: true

markdown: kramdown

google_analytics: UA-15831812-2

github_username: kapdap
rss: rss

minima:
  date_format: "%F %I:%M %p"

header_pages:
 - index.md
 - downloads.md
 - screenshots.md
 - LICENSE.md
 - about.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
