title: RE CVX SRT
author: Kapdap
email: kapdap@pm.me

product_name: RE CVX SRT
game_name: "Resident Evil: Code: Veronica"

provider_version: 0.9.0.1
interface_version: 0.9.0.0
directx_version: 0.9.0.1

show_excerpts: true

markdown: kramdown

github_username: kapdap
rss: rss

minima:
  date_format: "%F %I:%M %p"

header_pages:
 - index.md
 - downloads.md
 - screenshots.md
 - changelog.md
 - LICENSE.md
 - about.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
