title: RE CVX SRT
author: Kapdap
email: kapdap@pm.me

product_name: RE CVX SRT
game_name: "Resident Evil: Code: Veronica"

show_excerpts: true

markdown: kramdown

google_analytics: G-FP2WBZN98G

github_username: kapdap
rss: rss

minima:
  date_format: "%F %I:%M %p"

header_pages:
 - index.md
 - LICENSE.md
 - about.md

remote_theme: jekyll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-remote-theme
